[package]
name = "rs2048"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data_grid = { path = "../data_grid" }
pancurses = { version = "0.17.0", features = ["win32"] }
rand = "0.8.5"
